### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by MrJadaml** [santip/layout-manager#7]
Uncaught TypeError: Cannot read property '0' of undefined

**Atom Version**: 0.156.0
**System**: Mac OS X 10.9.5
**Thrown From**: [layout-manager](https://github.com/santip/layout-manager) package, v0.2.3
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At /Users/Jadam/.atom/packages/layout-manager/lib/layout-manager.coffee:49

TypeError: Cannot read property '0' of undefined
  at Object.module.exports.move (/Users/Jadam/.atom/packages/layout-manager/lib/layout-manager.coffee:49:6)
  at Object.module.exports.moveRight (/Users/Jadam/.atom/packages/layout-manager/lib/layout-manager.coffee:31:18)
  at atom-workspace.<anonymous> (/Users/Jadam/.atom/packages/layout-manager/lib/layout-manager.coffee:8:70)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by doches** [comment]
+1. Seems to happen when I attempt to move a pane too far to the left or right (as in, I have two panes open, focus in the left, and hit 'move tab to the right' multiple times in quick succession).

**Comment by adamgranted** [comment]
+1. I'm getting this error while using the key combination "Command + Control + Shift + Arrow Key" (Any arrow direction). I can't get any tabs to split into a new pane using that key combination, it just errors out for me. It will still split into a pane when right clicking on the tab and selecting the split option though.. 

Also I can still use the "Command + Option + - or =" for resizing -- providing they're already in a pane of course.
